spring.application.name=crm
# ↑ మన app పేరు

# DATABASE CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/estateflow_db
# ↑ MySQL లో estateflow_db కి connect అవుతుంది

spring.datasource.username=root
# ↑ MySQL username

spring.datasource.password=Admin@123
# ↑ MySQL password (మీరు పెట్టిన password)

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ↑ MySQL driver

# JPA SETTINGS
spring.jpa.hibernate.ddl-auto=update
# ↑ update = tables automatically create/update అవుతాయి
#   మనం manually create చేయక్కర్లేదు!

spring.jpa.show-sql=true
# ↑ SQL queries terminal లో కనిపిస్తాయి
#   debugging కి useful

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# ↑ MySQL తో communicate చేయడానికి

# SERVER PORT
server.port=8080
# ↑ Spring Boot localhost:8080 లో run అవుతుంది